//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHVacancy.Storage {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HHVacancy.Storage.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE VIEW VacancyFullInfo
        ///AS
        ///SELECT
        ///    v.VacancyId,
        ///    v.Name AS VacancyName,
        ///    a.Name AS AreaName,
        ///    e.Name AS EmployerName,
        ///    v.HasTest,
        ///    v.PublishedAt,
        ///    v.ResponseLetterRequired,
        ///    v.SalaryCurrency,
        ///    v.SalaryFrom,
        ///    v.SalaryTo,
        ///    v.SalaryGross,
        ///    v.SnippetRequirement,
        ///    v.SnippetResponsibility,
        ///    vt.Name AS VacancyTypeName,
        ///    v.Url,
        ///    v.AcceptTemporary,
        ///    v.Address,
        ///    v.AdvResponseUrl,
        ///    v.Archived,
        ///    v.Contacts,
        ///    v.CreatedAt,
        ///    v.ResponseUrl,
        ///    s.Name AS [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CreateVacancyFullInfoView {
            get {
                return ResourceManager.GetString("CreateVacancyFullInfoView", resourceCulture);
            }
        }
    }
}
